trigger:
  branches:
    include:
      - main
  paths:
    exclude: 
    - manifests/* 

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker login -u shashankbarsin -p $(password)
        docker build -f Dockerfile -t shashankbarsin/demo-app:1.0.1 .
        docker push shashankbarsin/demo-app:1.0.1
